name: Check Repository health

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Check Formatting
        run: npm run eslint:check && npm run prettier:check
      - name: Run tests
        run: npm test
